<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-03-15">

<title>CmdStan and OCI Images</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>




<link rel="stylesheet" href="../assets/sakura.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">CmdStan and OCI Images</h1>

<p class="date">2024-03-15</p>
</header>


<p><a href="https://mc-stan.org/users/interfaces/cmdstan">CmdStan</a> is a heavy dependency when building docker/OCI images. On the latest <code>debian:testing-slim</code>, it requires 1.3G of space.</p>
<pre class="shell"><code>root@49237339e848:~# du -h -s ~/.cmdstan
1.3G    /root/.cmdstan</code></pre>
<p>The typical compilation pipeline for <code>CmdStan</code> is to go from Stan -&gt; C++ -&gt; Executable Binary. If your Stan model can be pre-compiled as part of the image build, then you can use a <a href="https://docs.docker.com/build/building/multi-stage/">multi-stage build</a> to compile the model binary and copy it into a fresh image without the CmdStan libraries.</p>
<p>The only caveat is that we need to include any shared libraries that may be linked into the model binary. We can get a list using <code>ldd</code>. In this case I’ll use the example model found in <code>examples/bernoulli/bernoulli.stan</code> in the CmdStan installation directory.</p>
<pre class="shell"><code>root@49237339e848:~/.cmdstan/cmdstan-2.34.1/examples/bernoulli# ldd bernoulli
        linux-vdso.so.1 (0x00007ffc979bc000)
        libtbb.so.2 =&gt; /root/.cmdstan/cmdstan-2.34.1/stan/lib/stan_math/lib/tbb/libtbb.so.2 (0x000078044df98000)
        libstdc++.so.6 =&gt; /lib/x86_64-linux-gnu/libstdc++.so.6 (0x000078044dc00000)
        libm.so.6 =&gt; /lib/x86_64-linux-gnu/libm.so.6 (0x000078044deb6000)
        libgcc_s.so.1 =&gt; /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000078044de89000)
        libc.so.6 =&gt; /lib/x86_64-linux-gnu/libc.so.6 (0x000078044da1e000)
        /lib64/ld-linux-x86-64.so.2 (0x000078044e1c0000)</code></pre>
<p>The output shows that CmdStan links to a locally bundled copy of the Intel TBB library, the exact path depends on where you’ve installed CmdStan. Regardless of whether your model uses TBB, Stan will always link to it and set the <a href="https://en.wikipedia.org/wiki/Rpath">rpath</a> to the local CmdStan directory.</p>
<p>So, we’ll also copy over <code>libtbb.so.2</code> and I’ll use <a href="https://github.com/NixOS/patchelf"><code>patchelf</code></a> to modify the <code>rpath</code> of the model binary to point to the new directory.</p>
<p>All together, we end up with the following Containerfile where again I’m using the example <code>bernoulli</code> model included with CmdStan.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode Dockerfile"><code class="sourceCode dockerfile"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> debian:testing-slim <span class="kw">AS</span> base</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="kw">RUN</span> <span class="ex">apt-get</span> update <span class="kw">&amp;&amp;</span> <span class="dt">\</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="ex">apt-get</span> install <span class="at">-y</span> <span class="at">--no-install-recommends</span> build-essential ca-certificates curl patchelf <span class="kw">&amp;&amp;</span> <span class="dt">\</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rm</span> <span class="at">-rf</span> /var/lib/apt/lists/<span class="pp">*</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> base <span class="kw">AS</span> cmdstan</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="kw">ARG</span> CMDSTAN_VERSION=2.34.1</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="kw">RUN</span> <span class="ex">curl</span> <span class="at">-LO</span> https://github.com/stan-dev/cmdstan/releases/download/v<span class="va">${CMDSTAN_VERSION}</span>/cmdstan-<span class="va">${CMDSTAN_VERSION}</span>.tar.gz <span class="dt">\</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">&amp;&amp;</span> <span class="fu">mkdir</span> <span class="at">-p</span> cmdstan <span class="dt">\</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">&amp;&amp;</span> <span class="fu">tar</span> <span class="at">-xzf</span> cmdstan-<span class="va">${CMDSTAN_VERSION}</span>.tar.gz <span class="at">--strip</span> 1 <span class="at">-C</span> cmdstan</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="kw">WORKDIR</span> /cmdstan</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="kw">RUN</span> <span class="fu">make</span> <span class="at">-j</span><span class="va">$(</span><span class="fu">nproc</span><span class="va">)</span> examples/bernoulli/bernoulli <span class="kw">&amp;&amp;</span> <span class="dt">\</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="ex">patchelf</span> <span class="at">--set-rpath</span> /usr/local/lib examples/bernoulli/bernoulli <span class="kw">&amp;&amp;</span> <span class="dt">\</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">strip</span> <span class="at">-s</span> examples/bernoulli/bernoulli</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> base</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="kw">RUN</span> <span class="ex">apt-get</span> update <span class="kw">&amp;&amp;</span> <span class="dt">\</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="ex">apt-get</span> install <span class="at">-y</span> <span class="at">--no-install-recommends</span> r-base-core <span class="kw">&amp;&amp;</span> <span class="dt">\</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rm</span> <span class="at">-rf</span> /var/lib/apt/lists/<span class="pp">*</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="kw">RUN</span> <span class="fu">mkdir</span> /project</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="kw">WORKDIR</span> /project</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="kw">RUN</span> <span class="ex">Rscript</span> <span class="at">-e</span> <span class="st">"install.packages('cmdstanr', repos = c('https://mc-stan.org/r-packages/', getOption('repos')))"</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="kw">COPY</span> analysis.R ./</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="kw">COPY</span> <span class="op">--from=cmdstan</span> /cmdstan/examples/bernoulli/bernoulli bernoulli</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="kw">COPY</span> <span class="op">--from=cmdstan</span> /cmdstan/stan/lib/stan_math/lib/tbb/libtbb.so.2 /usr/local/lib/libtbb.so.2</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="kw">CMD</span> <span class="ex">Rscript</span> analysis.R</span></code></pre></div>
<p>The <code>analysis.R</code> file that is also being copied into the image is just a basic script that generates some simulated data and runs the pre-compiled model using <code>cmdstanr</code>. However, there are two important things to note. First, we use the <code>exe_file</code> argument to <code>cmdstan_model</code> to specify that our stan model has already been compiled.</p>
<p>Second, <code>cmdstanr</code> will error if there is not a local copy of CmdStan available. This is not because we actually need to call out to CmdStan, but rather the function <code>cmdstan_version</code>, which is used for several version checks, relies on <code>cmdstan_path()</code> being properly set. Since we know exactly which version we’ve used to compile our model, we’re going to override the <code>cmdstan_version</code> function within the <code>cmdstanr</code> package namespace to return a constant using the R function <code>assignInNamespace</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#!/usr/bin/env Rscript</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(cmdstanr))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">mc.cores =</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>())</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Force cmdstanr to not check the version using a locally installed</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># copy of CmdStan</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">assignInNamespace</span>(<span class="st">"cmdstan_version"</span>, <span class="cf">function</span>(...) <span class="st">"2.34.1"</span>, <span class="at">ns =</span> <span class="st">"cmdstanr"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">N =</span> <span class="dv">20</span>, <span class="at">y =</span> <span class="fu">rbinom</span>(<span class="dv">20</span>, <span class="dv">1</span>, <span class="fl">0.3</span>))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">cmdstan_model</span>(<span class="at">exe_file =</span> <span class="st">"bernoulli"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> mod<span class="sc">$</span><span class="fu">sample</span>(<span class="at">data =</span> data, <span class="at">refresh =</span> <span class="dv">0</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>fit<span class="sc">$</span><span class="fu">summary</span>()</span></code></pre></div>
</div>
<p>Let’s build our image and run a container.</p>
<pre class="shell"><code>$ podman build --jobs $(nproc) -t stan .
$ podman images
REPOSITORY                TAG           IMAGE ID      CREATED            SIZE
localhost/stan            latest        e5f6927fe990  3 minutes ago      568 MB
localhost/full-cmdstan    latest        a3dc48251dde  About an hour ago  1.81 GB
$ podman run stan
Running MCMC with 4 chains, at most 16 in parallel...

Chain 1 finished in 0.0 seconds.
Chain 2 finished in 0.0 seconds.
Chain 3 finished in 0.0 seconds.
Chain 4 finished in 0.0 seconds.

All 4 chains finished successfully.
Mean chain execution time: 0.0 seconds.
Total execution time: 0.3 seconds.

# A tibble: 2 x 10
  variable    mean  median     sd    mad       q5     q95  rhat ess_bulk
  &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
1 lp__     -12.3   -12.0   0.736  0.325  -13.8    -11.8    1.00    1649.
2 theta      0.227   0.220 0.0871 0.0890   0.0960   0.378  1.00    1402.</code></pre>
<p>The <code>full-cmdstan:latest</code> image is also derived from <code>debian:testing-slim</code>; however, it does not use a multi-stage build and instead includes a copy of CmdStan installed through <code>install_cmdstan()</code>. When compared to our slimmed down image, a reduction from 1.81 GB to 568 MB is not too bad.</p>





</body></html>