#!/usr/bin/env zsh

setopt err_return

if [[ ! -d $1 ]]; then
  print -u 2 "Usage: fix-links <directory>"
  exit 1
fi

for i in $1/*.html; do
    print "Adjusting file paths for $i"
    sed -i -r -e "s/(${i:t:r}_files)/\.\.\/assets\/\1/" $i
done
